// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCO7QG94M7ZMzbAADxFmsht-CIkvPddxTI',
    appId: '1:588592111690:web:e5cf215238a4bef74946b3',
    messagingSenderId: '588592111690',
    projectId: 'fit-mirror-2213d',
    authDomain: 'fit-mirror-2213d.firebaseapp.com',
    storageBucket: 'fit-mirror-2213d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXhjeAb8RPmT0naiRDXXm2zvi5Y1OS1ZU',
    appId: '1:588592111690:android:a86171c3edd6af014946b3',
    messagingSenderId: '588592111690',
    projectId: 'fit-mirror-2213d',
    storageBucket: 'fit-mirror-2213d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5sb7H2fVqzhPQSF7CjGU-SP8KY_LxD88',
    appId: '1:588592111690:ios:1e7ea77e10b1e9fb4946b3',
    messagingSenderId: '588592111690',
    projectId: 'fit-mirror-2213d',
    storageBucket: 'fit-mirror-2213d.firebasestorage.app',
    iosBundleId: 'com.example.fitMirrorProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5sb7H2fVqzhPQSF7CjGU-SP8KY_LxD88',
    appId: '1:588592111690:ios:1e7ea77e10b1e9fb4946b3',
    messagingSenderId: '588592111690',
    projectId: 'fit-mirror-2213d',
    storageBucket: 'fit-mirror-2213d.firebasestorage.app',
    iosBundleId: 'com.example.fitMirrorProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCO7QG94M7ZMzbAADxFmsht-CIkvPddxTI',
    appId: '1:588592111690:web:c2232a26b2222d4e4946b3',
    messagingSenderId: '588592111690',
    projectId: 'fit-mirror-2213d',
    authDomain: 'fit-mirror-2213d.firebaseapp.com',
    storageBucket: 'fit-mirror-2213d.firebasestorage.app',
  );
}